### ISSUE TITLE
Several Identities for an Address

### ISSUE THREAD

**Issue by 0xpeho** [Itheum/datametaverse-evm#4]
We need to address the issue that an address can be added to several identities like this:

1. address A deploys an identity via the identity factory
2. address A can then add address B

3. address C deploys an identity via the identity factory
4. address C can then also add address B

5. when we then load identity for address B we get two identities

**Comment by newbreedofgeek** [comment]
Closed so that discussion goes into - https://github.com/Itheum/datametaverse-evm/issues/7
